#version: '3.8'
services:
  db:
    image: mysql:8
    container_name: fma_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db:/var/lib/mysql
#      - /opt/homebrew/var/mysql/rental_mysqldb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p$${DB_PASSWORD}" ]
      timeout: 5s
      retries: 5
      interval: 5s

  migrate:
    build: .
    container_name: fma_migrate
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
    volumes:
      - .:/fma

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fma_web
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}

  nginx:
    image: nginx:latest
    container_name: fma_nginx
    ports:
      - "80:80" # Открываем стандартный порт для сайтов
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/fma/static
    depends_on:
      - web

volumes:
  static_volume: