# Generated by Django 6.1.1 on 2026-09-10 22:03

import apps.users.managers.users
import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID Primary Key', primary_key=True, serialize=False, verbose_name='UUID pk')),
                ('username', models.CharField(blank=True, help_text='Specified Username', max_length=50, verbose_name='Username')),
                ('email', models.EmailField(help_text='Your email', max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last name')),
                ('birth_date', models.DateField(blank=True, help_text='Your birthday', null=True, verbose_name='Birthday')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, default='', help_text='Specified phone number', max_length=75, verbose_name='Phone number')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date of join', verbose_name='Joined at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(help_text='Date of deletion', null=True, verbose_name='Deleted at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', apps.users.managers.users.UserSoftDeleteManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
