# Generated by Django 6.1.1 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date of deletion', null=True, verbose_name='Deleted at'),
        ),
    ]
