# Generated by Django 6.1.1 on 2026-09-11 19:12

import apps.users.validators.validate_birth_date_age
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your birthday', null=True, validators=[apps.users.validators.validate_birth_date_age.validate_birth_date], verbose_name='Birthday'),
        ),
    ]
