# Generated by Django 6.1.1 on 2026-09-15 17:33

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_user_fma_user_email_idx_user_fma_user_fullname_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.get_avatar_upload_path, verbose_name='Avatar'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='unique_user_phone', violation_error_message='A user with this phone number already exists!'),
        ),
    ]
