# Generated by Django 6.1.1 on 2026-09-15 18:26

import apps.users.managers.users
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_user_unique_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.users.UserSoftDeleteManager()),
                ('all_objects', apps.users.managers.users.AllUserSoftDeleteManager()),
            ],
        ),
    ]
