# Generated by Django 6.1.1 on 2026-09-15 23:15

import apps.core.utils.file_validators
import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.get_avatar_upload_path, validators=[apps.core.utils.file_validators.validate_extension, apps.core.utils.file_validators.validate_file_size], verbose_name='Avatar'),
        ),
    ]
