# Generated by Django 6.1.1 on 2026-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Specified phone number', max_length=75, null=True, unique=True, verbose_name='Phone number'),
        ),
    ]
