# Generated by Django 6.1.1 on 2026-09-10 22:03

import apps.listings.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID Primary Key', primary_key=True, serialize=False, verbose_name='UUID pk')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(help_text='Date of deletion', null=True, verbose_name='Deleted at')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Listing's Title")),
                ('description', models.TextField(verbose_name="Listing's description")),
                ('country', models.SmallIntegerField(choices=[(31, 'Azerbaijan'), (51, 'Armenia'), (156, 'China'), (268, 'Georgia'), (356, 'India'), (360, 'Indonesia'), (376, 'Israel'), (392, 'Japan'), (398, 'Kazakhstan'), (417, 'Kyrgyzstan'), (458, 'Malaysia'), (410, 'South Korea'), (158, 'Taiwan'), (762, 'Tajikistan'), (764, 'Thailand'), (792, 'Turkey'), (795, 'Turkmenistan'), (784, 'United Arab Emirates'), (860, 'Uzbekistan'), (704, 'Vietnam'), (40, 'Austria'), (112, 'Belarus'), (56, 'Belgium'), (100, 'Bulgaria'), (196, 'Cyprus'), (203, 'Czechia'), (208, 'Denmark'), (246, 'Finland'), (250, 'France'), (276, 'Germany'), (300, 'Greece'), (348, 'Hungary'), (372, 'Ireland'), (380, 'Italy'), (498, 'Moldova'), (528, 'Netherlands'), (578, 'Norway'), (616, 'Poland'), (620, 'Portugal'), (642, 'Romania'), (643, 'Russia'), (688, 'Serbia'), (724, 'Spain'), (752, 'Sweden'), (756, 'Switzerland'), (804, 'Ukraine'), (826, 'United Kingdom'), (32, 'Argentina'), (76, 'Brazil'), (124, 'Canada'), (484, 'Mexico'), (840, 'United States'), (36, 'Australia'), (818, 'Egypt'), (554, 'New Zealand'), (710, 'South Africa')], default=276, help_text='Selected country', verbose_name='Country')),
                ('district', models.CharField(help_text='Specified district', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='District')),
                ('city', models.CharField(help_text='Specified city', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='City')),
                ('street', models.CharField(help_text='Specified street', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Street')),
                ('house_number', models.CharField(help_text='Specified house number', max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='House number')),
                ('apartment_number', models.CharField(blank=True, help_text='Specified apartment number', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Apartment number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available?')),
                ('max_guests', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=2, help_text='Selected guests max quantity', verbose_name='Max guests')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('house', 'House'), ('townhouse', 'Townhouse'), ('room', 'Room'), ('loft', 'Loft')], default='apartment', help_text='Selected Property Type', max_length=15, verbose_name='Property type')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current price per night')),
                ('rooms', models.SmallIntegerField(choices=[(0, '0 Rooms (Studio / Loft)'), (1, '1 Room'), (2, '2 Rooms'), (3, '3 Rooms'), (4, '4 Rooms'), (5, '5+ Rooms')], default=1, help_text="Selected room's quantity", verbose_name='Rooms')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'db_table': 'fma_listings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID Primary Key', primary_key=True, serialize=False, verbose_name='UUID pk')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(help_text='Date of deletion', null=True, verbose_name='Deleted at')),
                ('photo', models.ImageField(upload_to=apps.listings.models.get_upload_path)),
                ('photo_number', models.PositiveSmallIntegerField(help_text='Specified photo number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Photo number')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'fma_photos',
                'ordering': ('-created_at',),
            },
        ),
    ]
