# Generated by Django 6.1.1 on 2026-09-10 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(help_text='Current selected user', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='photo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='listings.listing', verbose_name='Listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'price_per_night'], name='fma_listings_city_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'rooms'], name='fma_listings_city_rooms_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'price_per_night', 'rooms'], name='fma_list_city_price_rooms_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='fma_listings_city_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_night'], name='fma_listings_price_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['rooms'], name='fma_listings_rooms_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('user', 'country', 'city', 'district', 'street', 'house_number', 'apartment_number'), name='unique_user_address', violation_error_message='Such an address combination already exists!'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['listing', 'photo_number'], name='fma_listing_photo_number_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['photo_number'], name='fma_photo_number_idx'),
        ),
    ]
