# Generated by Django 6.1.1 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date of deletion', null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date of deletion', null=True, verbose_name='Deleted at'),
        ),
    ]
