# Generated by Django 6.1.1 on 2026-09-12 19:44

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_deleted_at_alter_photo_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Discount coefficient for price per night', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Discount'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gt', Decimal('0')), ('discount__lte', Decimal('1'))), name='discount_from_0.01_to_1', violation_error_message='Discount is only allowed in range of (0.01 and 1.00).'),
        ),
    ]
