# Generated by Django 6.1.1 on 2026-09-13 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_discount_listing_discount_from_0_01_to_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['district'], name='fma_listings_district_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['street'], name='fma_listings_street_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['country'], name='fma_listings_country_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['title'], name='fma_listings_title_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['description'], name='fma_listings_description_idx'),
        ),
    ]
