# Generated by Django 6.1.1 on 2026-09-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_fma_listings_district_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('listing', 'photo_number'), name='unique_listing_photo_number', violation_error_message='Photo with this number already exists for this listing!'),
        ),
    ]
