# Generated by Django 6.1.1 on 2026-09-15 23:15

import apps.core.utils.file_validators
import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_photo_unique_listing_photo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=apps.listings.models.get_upload_path, validators=[apps.core.utils.file_validators.validate_extension, apps.core.utils.file_validators.validate_file_size], verbose_name='Photo'),
        ),
    ]
