# Generated by Django 6.1.1 on 2026-09-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='photo',
            name='fma_listing_photo_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='fma_photo_number_idx',
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['listing'], name='fma_listing_idx'),
        ),
    ]
