# Generated by Django 6.1.1 on 2026-09-17 18:50

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_photo_fma_listing_photo_number_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='fma_listings_description_idx',
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(django.db.models.functions.text.Length('description', length=500), name='fma_listings_description_idx'),
        ),
    ]
