# Generated by Django 6.1.1 on 2026-09-21 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_fma_listings_description_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_user_address',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('user', 'country', 'city', 'district', 'street', 'house_number'), name='unique_user_address', violation_error_message='Such an address combination already exists!'),
        ),
    ]
