# Generated by Django 6.1.1 on 2026-09-26 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listing_unique_user_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_user_address',
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('apartment_number__isnull', False)), fields=('user', 'country', 'city', 'district', 'street', 'house_number', 'apartment_number'), name='unique_user_apartment_address', violation_error_message='You have already registered a property at this exact apartment address!'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('apartment_number__isnull', True)), fields=('user', 'country', 'city', 'district', 'street', 'house_number'), name='unique_user_standalone_house_address', violation_error_message='You have already registered a standalone property at this exact apartment address!'),
        ),
    ]
