# Generated by Django 6.1.1 on 2026-09-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_listing_unique_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_user_apartment_address',
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_user_standalone_house_address',
        ),
        migrations.RemoveConstraint(
            model_name='photo',
            name='unique_listing_photo_number',
        ),
    ]
