# Generated by Django 6.1.1 on 2026-09-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listing_unique_user_apartment_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='fma_listings_description_idx',
        ),
    ]
