# Generated by Django 6.1.1 on 2026-09-10 22:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID Primary Key', primary_key=True, serialize=False, verbose_name='UUID pk')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(help_text='Date of deletion', null=True, verbose_name='Deleted at')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text="Shows current booking's status", max_length=15, verbose_name="Booking's status")),
                ('guests_number', models.PositiveSmallIntegerField(help_text='Specified guests number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Guest number')),
                ('snapshot_data', models.JSONField(blank=True, verbose_name='Snapshot of current Listing data')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the stay', max_digits=10, verbose_name='Total price')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'fma_bookings',
                'ordering': ('-created_at',),
            },
        ),
    ]
