# Generated by Django 6.1.1 on 2026-09-10 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('guests_number__gte', 1), ('guests_number__lte', 10)), name='guests_from_1_to_10', violation_error_message='Guests number must be between 1 and 10!'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gt', models.F('date_from'))), name='start_date_gt_than_end_date', violation_error_message='Booking start date can not be greater than end date!'),
        ),
    ]
