# Generated by Django 6.1.1 on 2026-09-11 08:09

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('listings', '0003_alter_listing_price_per_night'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='start_date_gt_than_end_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price for the stay', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total price'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gt', models.F('date_from'))), name='end_date_gt_than_start_date', violation_error_message='Booking start date can not be greater than end date!'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='booking_total_price_gte_zero', violation_error_message='Total price can not be less than zero!'),
        ),
    ]
