# Generated by Django 6.1.1 on 2026-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_start_date_gt_than_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date of deletion', null=True, verbose_name='Deleted at'),
        ),
    ]
