# Generated by Django 6.1.1 on 2026-09-11 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_deleted_at'),
        ('listings', '0004_alter_listing_deleted_at_alter_photo_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='end_date_gt_than_start_date',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gt', models.F('date_from'))), name='end_date_gt_start_date', violation_error_message='Booking start date can not be greater than end date!'),
        ),
    ]
