# Generated by Django 6.1.1 on 2026-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_fma_bookings_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='snapshot_data',
            field=models.JSONField(default=dict, verbose_name='Snapshot of current Listing data'),
        ),
    ]
