# Generated by Django 6.1.1 on 2026-09-21 17:11

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_snapshot_data'),
        ('listings', '0011_remove_listing_unique_user_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique UUID Primary Key', verbose_name='UUID pk')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Date of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Date of update', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date of deletion', null=True, verbose_name='Deleted at')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', help_text="Shows current booking's status", max_length=15, verbose_name="Booking's status")),
                ('guests_number', models.PositiveSmallIntegerField(help_text='Specified guests number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Guest number')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='Snapshot of current Listing data')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for the stay', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total price')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='listings.listing', verbose_name='Listing')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical Booking',
                'verbose_name_plural': 'historical Bookings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
