# Generated by Django 6.1.1 on 2026-09-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_historicalbooking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalbooking',
            table='fma_bookings_historicalrecords',
        ),
    ]
