# Generated by Django 6.1.1 on 2026-09-10 22:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID Primary Key', primary_key=True, serialize=False, verbose_name='UUID pk')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date of update', verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(help_text='Date of deletion', null=True, verbose_name='Deleted at')),
                ('property_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('location_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(help_text="Review's text", max_length=1500, verbose_name="Review's text")),
                ('booking', models.OneToOneField(help_text='Associated Booking', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='bookings.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'fma_reviews',
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('property_rating__gte', 1), ('property_rating__lte', 5)), name='property_rating_1_to_5', violation_error_message='Property rating must be between 1 and 5!'), models.CheckConstraint(condition=models.Q(('location_rating__gte', 1), ('location_rating__lte', 5)), name='location_rating_1_to_5', violation_error_message='Location rating must be between 1 and 5!')],
            },
        ),
    ]
