# Generated by Django 6.1.1 on 2026-09-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_snapshot_data'),
        ('reviews', '0002_alter_review_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='fma_reviews_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['property_rating'], name='fma_reviews_prop_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['location_rating'], name='fma_reviews_loc_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='fma_reviews_booking_id_idx'),
        ),
    ]
