# Generated by Django 6.1.1 on 2026-09-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_fma_reviews_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
