# Generated by Django 6.1.1 on 2026-09-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_snapshot_data'),
        ('reviews', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['property_rating', 'location_rating'], name='fma_reviews_prop_loc_rat_idx'),
        ),
    ]
